
# Change these first
owner: SamPetherbridge # Your GitHub username
repo: status.httpstatus.xyz # Your GitHub repository name

# Add your sites here
sites:
  - name: 200 Ok - GET
    url: https://statuscodes.peth.me/200
    method: GET
    expectedStatusCodes:
      - 200
  - name: 200 Ok - POST
    url: https://statuscodes.peth.me/200
    method: POST
    expectedStatusCodes:
      - 200
  - name: 200 Ok - PUT
    url: https://statuscodes.peth.me/200
    method: PUT
    expectedStatusCodes:
      - 200
  - name: 200 Ok - PATCH
    url: https://statuscodes.peth.me/200
    method: PATCH
    expectedStatusCodes:
      - 200
  - name: 200 Ok - DELETE
    url: https://statuscodes.peth.me/200
    method: DELETE
    expectedStatusCodes:
      - 200
  - name: 200 Ok - COPY
    url: https://statuscodes.peth.me/200
    method: COPY
    expectedStatusCodes:
      - 200
  - name: 200 Ok - HEAD
    url: https://statuscodes.peth.me/200
    method: HEAD
    expectedStatusCodes:
      - 200
  - name: 200 Ok - OPTIONS
    url: https://statuscodes.peth.me/200
    method: OPTIONS
    expectedStatusCodes:
      - 200
  - name: 200 Ok - LOCK
    url: https://statuscodes.peth.me/200
    method: LOCK
    expectedStatusCodes:
      - 200
  - name: 200 Ok - UNLOCK
    url: https://statuscodes.peth.me/200
    method: UNLOCK
    expectedStatusCodes:
      - 200
  - name: 200 Ok - PROPFIND
    url: https://statuscodes.peth.me/200
    method: PROPFIND
    expectedStatusCodes:
      - 200
  - name: 201 - GET
    url: https://statuscodes.peth.me/201
    method: GET
    expectedStatusCodes:
      - 201
  - name: 202 - GET
    url: https://statuscodes.peth.me/202
    method: GET
    expectedStatusCodes:
      - 202
  - name: 203 - GET
    url: https://statuscodes.peth.me/203
    method: GET
    expectedStatusCodes:
      - 203
  - name: 204 - GET
    url: https://statuscodes.peth.me/204
    method: GET
    expectedStatusCodes:
      - 204
  - name: 205 - GET
    url: https://statuscodes.peth.me/205
    method: GET
    expectedStatusCodes:
      - 205
  - name: 206 - GET
    url: https://statuscodes.peth.me/206
    method: GET
    expectedStatusCodes:
      - 206
  - name: 207 - GET
    url: https://statuscodes.peth.me/207
    method: GET
    expectedStatusCodes:
      - 207
  - name: 208 - GET
    url: https://statuscodes.peth.me/208
    method: GET
    expectedStatusCodes:
      - 208
  - name: 226 - GET
    url: https://statuscodes.peth.me/226
    method: GET
    expectedStatusCodes:
      - 226
  - name: 300 - GET
    url: https://statuscodes.peth.me/300
    method: GET
    expectedStatusCodes:
      - 300
  - name: 301 - GET
    url: https://statuscodes.peth.me/301
    method: GET
    expectedStatusCodes:
      - 301
  - name: 302 - GET
    url: https://statuscodes.peth.me/302
    method: GET
    expectedStatusCodes:
      - 302
  - name: 303 - GET
    url: https://statuscodes.peth.me/303
    method: GET
    expectedStatusCodes:
      - 303
  - name: 304 - GET
    url: https://statuscodes.peth.me/304
    method: GET
    expectedStatusCodes:
      - 304
  - name: 307 - GET
    url: https://statuscodes.peth.me/307
    method: GET
    expectedStatusCodes:
      - 307
  - name: 308 - GET
    url: https://statuscodes.peth.me/308
    method: GET
    expectedStatusCodes:
      - 308
  - name: 400 - GET
    url: https://statuscodes.peth.me/400
    method: GET
    expectedStatusCodes:
      - 400
  - name: 401 - GET
    url: https://statuscodes.peth.me/401
    method: GET
    expectedStatusCodes:
      - 401
  - name: 402 - GET
    url: https://statuscodes.peth.me/402
    method: GET
    expectedStatusCodes:
      - 402
  - name: 403 - GET
    url: https://statuscodes.peth.me/403
    method: GET
    expectedStatusCodes:
      - 403
  - name: 404 - GET
    url: https://statuscodes.peth.me/404
    method: GET
    expectedStatusCodes:
      - 404
  - name: 405 - GET
    url: https://statuscodes.peth.me/405
    method: GET
    expectedStatusCodes:
      - 405
  - name: 406 - GET
    url: https://statuscodes.peth.me/406
    method: GET
    expectedStatusCodes:
      - 406
  - name: 407 - GET
    url: https://statuscodes.peth.me/407
    method: GET
    expectedStatusCodes:
      - 407
  - name: 408 - GET
    url: https://statuscodes.peth.me/408
    method: GET
    expectedStatusCodes:
      - 408
  - name: 409 - GET
    url: https://statuscodes.peth.me/409
    method: GET
    expectedStatusCodes:
      - 409
  - name: 410 - GET
    url: https://statuscodes.peth.me/410
    method: GET
    expectedStatusCodes:
      - 410
  - name: 411 - GET
    url: https://statuscodes.peth.me/411
    method: GET
    expectedStatusCodes:
      - 411
  - name: 412 - GET
    url: https://statuscodes.peth.me/412
    method: GET
    expectedStatusCodes:
      - 412
  - name: 413 - GET
    url: https://statuscodes.peth.me/413
    method: GET
    expectedStatusCodes:
      - 413
  - name: 414 - GET
    url: https://statuscodes.peth.me/414
    method: GET
    expectedStatusCodes:
      - 414
  - name: 415 - GET
    url: https://statuscodes.peth.me/415
    method: GET
    expectedStatusCodes:
      - 415
  - name: 416 - GET
    url: https://statuscodes.peth.me/416
    method: GET
    expectedStatusCodes:
      - 416
  - name: 417 - GET
    url: https://statuscodes.peth.me/417
    method: GET
    expectedStatusCodes:
      - 417
  - name: 418 - GET
    url: https://statuscodes.peth.me/418
    method: GET
    expectedStatusCodes:
      - 418
  - name: 421 - GET
    url: https://statuscodes.peth.me/421
    method: GET
    expectedStatusCodes:
      - 421
  - name: 422 - GET
    url: https://statuscodes.peth.me/422
    method: GET
    expectedStatusCodes:
      - 422
  - name: 423 - GET
    url: https://statuscodes.peth.me/423
    method: GET
    expectedStatusCodes:
      - 423
  - name: 424 - GET
    url: https://statuscodes.peth.me/424
    method: GET
    expectedStatusCodes:
      - 424
  - name: 425 - GET
    url: https://statuscodes.peth.me/425
    method: GET
    expectedStatusCodes:
      - 425
  - name: 426 - GET
    url: https://statuscodes.peth.me/426
    method: GET
    expectedStatusCodes:
      - 426
  - name: 428 - GET
    url: https://statuscodes.peth.me/428
    method: GET
    expectedStatusCodes:
      - 428
  - name: 429 - GET
    url: https://statuscodes.peth.me/429
    method: GET
    expectedStatusCodes:
      - 429
  - name: 431 - GET
    url: https://statuscodes.peth.me/431
    method: GET
    expectedStatusCodes:
      - 431
  - name: 451 - GET
    url: https://statuscodes.peth.me/451
    method: GET
    expectedStatusCodes:
      - 451
  - name: 500 - GET
    url: https://statuscodes.peth.me/500
    method: GET
    expectedStatusCodes:
      - 500
  - name: 501 - GET
    url: https://statuscodes.peth.me/501
    method: GET
    expectedStatusCodes:
      - 501
  - name: 502 - GET
    url: https://statuscodes.peth.me/502
    method: GET
    expectedStatusCodes:
      - 502
  - name: 503 - GET
    url: https://statuscodes.peth.me/503
    method: GET
    expectedStatusCodes:
      - 503
  - name: 504 - GET
    url: https://statuscodes.peth.me/504
    method: GET
    expectedStatusCodes:
      - 504
  - name: 505 - GET
    url: https://statuscodes.peth.me/505
    method: GET
    expectedStatusCodes:
      - 505
  - name: 506 - GET
    url: https://statuscodes.peth.me/506
    method: GET
    expectedStatusCodes:
      - 506
  - name: 507 - GET
    url: https://statuscodes.peth.me/507
    method: GET
    expectedStatusCodes:
      - 507
  - name: 508 - GET
    url: https://statuscodes.peth.me/508
    method: GET
    expectedStatusCodes:
      - 508
  - name: 509 - GET
    url: https://statuscodes.peth.me/509
    method: GET
    expectedStatusCodes:
      - 509
  - name: 510 - GET
    url: https://statuscodes.peth.me/510
    method: GET
    expectedStatusCodes:
      - 510
  - name: 511 - GET
    url: https://statuscodes.peth.me/511
    method: GET
    expectedStatusCodes:
      - 511
  - name: 520 - GET
    url: https://statuscodes.peth.me/520
    method: GET
    expectedStatusCodes:
      - 520
  - name: 521 - GET
    url: https://statuscodes.peth.me/521
    method: GET
    expectedStatusCodes:
      - 521
  - name: 522 - GET
    url: https://statuscodes.peth.me/522
    method: GET
    expectedStatusCodes:
      - 522
  - name: 523 - GET
    url: https://statuscodes.peth.me/523
    method: GET
    expectedStatusCodes:
      - 523
  - name: 524 - GET
    url: https://statuscodes.peth.me/524
    method: GET
    expectedStatusCodes:
      - 524
  - name: 525 - GET
    url: https://statuscodes.peth.me/525
    method: GET
    expectedStatusCodes:
      - 525
  - name: 526 - GET
    url: https://statuscodes.peth.me/526
    method: GET
    expectedStatusCodes:
      - 526
  - name: 527 - GET
    url: https://statuscodes.peth.me/527
    method: GET
    expectedStatusCodes:
      - 527
  - name: 530 - GET
    url: https://statuscodes.peth.me/530
    method: GET
    expectedStatusCodes:
      - 530
  - name: 598 - GET
    url: https://statuscodes.peth.me/598
    method: GET
    expectedStatusCodes:
      - 598
  - name: 599 - GET
    url: https://statuscodes.peth.me/599
    method: GET
    expectedStatusCodes:
      - 599

assignees:
  - SamPetherbridge

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.statuscodes.peth.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: statuscodes.peth.me - Status
  introTitle: "Status Codes - Peth.Me"
  introMessage: "Status page for https://statuscodes.peth.me powered by GitHub."
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"
